# Use an official Miniconda3 as a parent image
FROM continuumio/miniconda3

# Create a new Conda environment
RUN conda create -n rna_qc_env python=3.8 -y

# Activate the Conda environment
SHELL ["conda", "run", "-n", "rna_qc_env", "/bin/bash", "-c"]

# Install basic packages
RUN echo "source activate rna_qc_env" >> /etc/bash.bashrc && \
    conda install -y -c conda-forge anndata r-base xorg-libxt r-cairodevice && \
    conda clean -afy
    
# Install scanpy using pip
RUN pip install scanpy

# Set default command to activate the Conda environment and run /bin/bash
CMD ["/bin/bash", "--rcfile", "/opt/conda/etc/profile.d/conda.sh", "-i"]

  
# 1. docker build -t eilalan/rna_qc_env:latest -f Dockerfile_rna_qc .
# 2. docker run -it eilalan/rna_qc_env:latest bash
# 3. docker push eilalan/rna_qc_env:latest
